name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 325961785170.dkr.ecr.ap-southeast-1.amazonaws.com
      
      - name: Build & Push Docker Image
        run: |
          docker build -t demo-app .
          docker tag demo-app:latest 325961785170.dkr.ecr.ap-southeast-1.amazonaws.com/demo-app:latest
          docker push 325961785170.dkr.ecr.ap-southeast-1.amazonaws.com/demo-app:latest

      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --cluster demo-cluster --service demo-service --force-new-deployment
